apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2018-11-28T16:37:31Z'
  generation: 3
  labels:
    app: logtofile
  name: logtofile
  namespace: sidecar-container-logging
  resourceVersion: '444064'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/sidecar-container-logging/deploymentconfigs/logtofile
  uid: e6838adb-f32b-11e8-b028-025673be3232
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: logtofile
    deploymentconfig: logtofile
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: logtofile
        deploymentconfig: logtofile
    spec:
      containers:
        - args:
            - /bin/sh
            - '-c'
            - sleep 5 && tail -n+1 -f /tmp/datelog.txt
          image: 'docker.io/busybox:latest'
          imagePullPolicy: Always
          name: logging-sidecar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmp
        - image: >-
            docker.io/wkulhanek/logtofile@sha256:7b28abe15eb652b705b942a692e81e1a4a7e121a5079c5a3623dc1b345868168
          imagePullPolicy: Always
          name: logtofile
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: tmp
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - logtofile
        from:
          kind: ImageStreamTag
          name: 'logtofile:latest'
          namespace: sidecar-container-logging
        lastTriggeredImage: >-
          docker.io/wkulhanek/logtofile@sha256:7b28abe15eb652b705b942a692e81e1a4a7e121a5079c5a3623dc1b345868168
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2018-11-28T16:37:38Z'
      lastUpdateTime: '2018-11-28T16:37:38Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2018-11-28T17:05:54Z'
      lastUpdateTime: '2018-11-28T17:05:56Z'
      message: replication controller "logtofile-2" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: 'docker.io/busybox:latest'
        type: ImageChange
    message: image change
  latestVersion: 2
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
