apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.completed-at: 2018-11-28 19:08:09 +0000 UTC
    openshift.io/deployer-pod.created-at: 2018-11-28 19:07:56 +0000 UTC
    openshift.io/deployer-pod.name: logtofile-2-deploy
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: logtofile
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: ""
    openshift.io/deployment.status-reason: image change
    openshift.io/encoded-deployment-config: |
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"logtofile","namespace":"side-delete","selfLink":"/apis/apps.openshift.io/v1/namespaces/side-delete/deploymentconfigs/logtofile","uid":"1f8da09e-f33f-11e8-b028-025673be3232","resourceVersion":"466087","generation":3,"creationTimestamp":"2018-11-28T18:55:07Z","labels":{"app":"logtofile"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["logtofile"],"from":{"kind":"ImageStreamTag","namespace":"side-delete","name":"logtofile:latest"},"lastTriggeredImage":"docker.io/wkulhanek/logtofile@sha256:7b28abe15eb652b705b942a692e81e1a4a7e121a5079c5a3623dc1b345868168"}}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"logtofile","deploymentconfig":"logtofile"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"logtofile","deploymentconfig":"logtofile"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"volumes":[{"name":"tmp","emptyDir":{}}],"containers":[{"name":"logging-sidecar","image":"docker.io/busybox:latest","args":["/bin/sh","-c","sleep 5 \u0026\u0026 tail -n+1 -f /tmp/datelog.txt"],"resources":{},"volumeMounts":[{"name":"tmp","mountPath":"/tmp"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"},{"name":"logtofile","image":"docker.io/wkulhanek/logtofile@sha256:7b28abe15eb652b705b942a692e81e1a4a7e121a5079c5a3623dc1b345868168","resources":{},"volumeMounts":[{"name":"tmp","mountPath":"/tmp"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":2,"observedGeneration":2,"replicas":1,"updatedReplicas":1,"availableReplicas":1,"unavailableReplicas":0,"details":{"message":"image change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"DockerImage","name":"docker.io/busybox:latest"}}}]},"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2018-11-28T18:55:14Z","lastTransitionTime":"2018-11-28T18:55:14Z","message":"Deployment config has minimum availability."},{"type":"Progressing","status":"True","lastUpdateTime":"2018-11-28T18:55:14Z","lastTransitionTime":"2018-11-28T18:55:14Z","reason":"NewReplicationControllerAvailable","message":"replication controller \"logtofile-1\" successfully rolled out"}],"readyReplicas":1}}
  creationTimestamp: 2018-11-28T19:07:56Z
  generation: 2
  labels:
    app: logtofile
    openshift.io/deployment-config.name: logtofile
  name: logtofile-2
  namespace: side-delete
  ownerReferences:
  - apiVersion: apps.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: DeploymentConfig
    name: logtofile
    uid: 1f8da09e-f33f-11e8-b028-025673be3232
  resourceVersion: "466169"
  selfLink: /api/v1/namespaces/side-delete/replicationcontrollers/logtofile-2
  uid: ea506a0d-f340-11e8-b028-025673be3232
spec:
  replicas: 1
  selector:
    app: logtofile
    deployment: logtofile-2
    deploymentconfig: logtofile
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: "2"
        openshift.io/deployment-config.name: logtofile
        openshift.io/deployment.name: logtofile-2
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: logtofile
        deployment: logtofile-2
        deploymentconfig: logtofile
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - sleep 5 && tail -n+1 -f /tmp/datelog.txt
        image: docker.io/busybox:latest
        imagePullPolicy: Always
        name: logging-sidecar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      - image: docker.io/wkulhanek/logtofile@sha256:7b28abe15eb652b705b942a692e81e1a4a7e121a5079c5a3623dc1b345868168
        imagePullPolicy: Always
        name: logtofile
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1