apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for
        container logging-sidecar; cpu, memory limit for container logging-sidecar;
        cpu, memory request for container logtofile; cpu, memory limit for container
        logtofile'
      openshift.io/deployment-config.latest-version: "2"
      openshift.io/deployment-config.name: logtofile
      openshift.io/deployment.name: logtofile-2
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/scc: restricted
    creationTimestamp: 2018-11-28T19:08:02Z
    generateName: logtofile-2-
    labels:
      app: logtofile
      deployment: logtofile-2
      deploymentconfig: logtofile
    name: logtofile-2-r2gsl
    namespace: side-delete
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: logtofile-2
      uid: ea506a0d-f340-11e8-b028-025673be3232
    resourceVersion: "466154"
    selfLink: /api/v1/namespaces/side-delete/pods/logtofile-2-r2gsl
    uid: ed6600e0-f340-11e8-b028-025673be3232
  spec:
    containers:
    - args:
      - /bin/sh
      - -c
      - sleep 5 && tail -n+1 -f /tmp/datelog.txt
      image: docker.io/busybox:latest
      imagePullPolicy: Always
      name: logging-sidecar
      resources:
        limits:
          cpu: 500m
          memory: 1536Mi
        requests:
          cpu: 50m
          memory: 256Mi
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
        runAsUser: 1002300000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /tmp
        name: tmp
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-f88m8
        readOnly: true
    - image: docker.io/wkulhanek/logtofile@sha256:7b28abe15eb652b705b942a692e81e1a4a7e121a5079c5a3623dc1b345868168
      imagePullPolicy: Always
      name: logtofile
      resources:
        limits:
          cpu: 500m
          memory: 1536Mi
        requests:
          cpu: 50m
          memory: 256Mi
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
        runAsUser: 1002300000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /tmp
        name: tmp
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-f88m8
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-5kjqv
    nodeName: node7.4df4.internal
    nodeSelector:
      env: users
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1002300000
      seLinuxOptions:
        level: s0:c48,c22
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    volumes:
    - emptyDir: {}
      name: tmp
    - name: default-token-f88m8
      secret:
        defaultMode: 420
        secretName: default-token-f88m8
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2018-11-28T19:08:02Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2018-11-28T19:08:07Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2018-11-28T19:08:02Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://149f82b882d8652ee85c9dbc4b6f3f6a01d956392b27192a77ab1da62f78cf1a
      image: docker.io/busybox:latest
      imageID: docker-pullable://docker.io/busybox@sha256:2a03a6059f21e150ae84b0973863609494aad70f0a80eaeb64bddd8d92465812
      lastState: {}
      name: logging-sidecar
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2018-11-28T19:08:05Z
    - containerID: docker://f79fa52357206f776b4f78ba4cc8482fe8a8719527e2e07db1ab7ead07b02e0b
      image: docker.io/wkulhanek/logtofile@sha256:7b28abe15eb652b705b942a692e81e1a4a7e121a5079c5a3623dc1b345868168
      imageID: docker-pullable://docker.io/wkulhanek/logtofile@sha256:7b28abe15eb652b705b942a692e81e1a4a7e121a5079c5a3623dc1b345868168
      lastState: {}
      name: logtofile
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2018-11-28T19:08:07Z
    hostIP: 192.199.0.79
    phase: Running
    podIP: 10.1.14.139
    qosClass: Burstable
    startTime: 2018-11-28T19:08:02Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
